### ISSUE TITLE
法学院毕业论文

### ISSUE THREAD

**Issue by yindehao** [shadowofgost/sudathesis-soochow-university-latex-template#2]
请问这个模板可以支持法学院毕业论文的参考文献格式吗，目前网上找不到符合法学院的毕业论文Latex模板。

具体注释条例如下：

1.著作类
胡长清：《中国民法总论》，中国政法大学出版社1997年版，第20页。
陈计男：《民事诉讼法论》（上）（增订三版三刷），三民书局股份有限公司2006年版，第6-10页。
2.论文类
吴俊：《债务人异议之诉的实体基础与程序构造》，载《中国政法大学学报》2023年第2期，第163-164页。
苏永钦：《私法自治中的国家强制》，载《中外法学》2001年第1期，第9页。
[指导文件2 注释及参考文献体例.docx](https://github.com/user-attachments/files/18192167/2.docx)

**Comment by shadowofgost** [comment]
您好，抱歉，这个latex模板无法支持这种奇怪的参考文献要求。这个latex模板是基于清华的基础上做的，参考文献部分并没有因此做大的更改，清华模板不支持这种参考文献的格式，所以此模板也不支持。并且个人能力有限，我并不理解bbx和bst的文件内容，所以也无法针对此要求进行更改。并且此模板用于支持苏州大学的毕业文件要求，目前暂未收到消息法学院会有这种参考文献格式要求，所以目前也不会有相关规划，抱歉。

> 请问这个模板可以支持法学院毕业论文的参考文献格式吗，目前网上找不到符合法学院的毕业论文Latex模板。
> 
> 具体注释条例如下：
> 
> 1.著作类 胡长清：《中国民法总论》，中国政法大学出版社1997年版，第20页。 陈计男：《民事诉讼法论》（上）（增订三版三刷），三民书局股份有限公司2006年版，第6-10页。 2.论文类 吴俊：《债务人异议之诉的实体基础与程序构造》，载《中国政法大学学报》2023年第2期，第163-164页。 苏永钦：《私法自治中的国家强制》，载《中外法学》2001年第1期，第9页。 [指导文件2 注释及参考文献体例.docx](https://github.com/user-attachments/files/18192167/2.docx)

您好，抱歉，这个latex模板无法支持这种奇怪的参考文献要求。这个latex模板是基于清华的基础上做的，参考文献部分并没有因此做大的更改，清华模板不支持这种参考文献的格式，所以此模板也不支持。并且个人能力有限，我并不理解bbx和bst的文件内容，所以也无法针对此要求进行更改。并且此模板用于支持苏州大学的毕业文件要求，目前暂未收到消息法学院会有这种参考文献格式要求，所以目前也不会有相关规划，抱歉。

**Comment by shadowofgost** [comment]
> 请问这个模板可以支持法学院毕业论文的参考文献格式吗，目前网上找不到符合法学院的毕业论文Latex模板。
> 
> 具体注释条例如下：
> 
> 1.著作类 胡长清：《中国民法总论》，中国政法大学出版社1997年版，第20页。 陈计男：《民事诉讼法论》（上）（增订三版三刷），三民书局股份有限公司2006年版，第6-10页。 2.论文类 吴俊：《债务人异议之诉的实体基础与程序构造》，载《中国政法大学学报》2023年第2期，第163-164页。 苏永钦：《私法自治中的国家强制》，载《中外法学》2001年第1期，第9页。 [指导文件2 注释及参考文献体例.docx](https://github.com/user-attachments/files/18192167/2.docx)

您可以申请向清华大学的latex模板提出建议，考虑到star数量和活跃人数，我想清华模板会添加相关的功能，尤其是这个是法学专业通用的参考文献标准的话。或者向本校的latex模板提出issue
